name: build-pr

on:
  pull_request:

permissions:
  contents: read

jobs:
  linux-deb:
    name: Linux build
    uses: ./.github/workflows/linux.yml
    with:
      artifact-prefix: qteasytier-pr-${{ github.event.pull_request.number }}

  windows-zip:
    name: Windows build amd64
    uses: ./.github/workflows/windows.yml
    with:
      artifact-prefix: qteasytier-pr-${{ github.event.pull_request.number }}

  deepin-dtk:
    name: Deepin v25 DTK build
    uses: ./.github/workflows/deepin.yml
    with:
      artifact-name: qteasytier-pr-${{ github.event.pull_request.number }}-deepin
